name: CI Tests and Lint

on:
  push:
    branches:
      - main
jobs:
  test-lint:
    runs-on: ubuntu-latest

steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run flake8
      run: flake8 src/

    - name: Run unit tests
      run: pytest -v
